// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

/// @dev Runtime code is installed only through eth_call state overrides.
contract Simulator {
    struct Call {
        address target;
        bool allowFailure;
        bool checkReturn;
        uint256 value;
        bytes data;
    }

    struct Balance { address token; address account; }
    struct Result { bool success; bytes data; uint256 gasUsed; }

    error CallFailed(uint256 index, bytes reason);
    error ValueMismatch();
    error TransferFailed();

    function simulate(Call[] calldata calls, Balance[] calldata balances) external payable
        returns (uint256[] memory before_, uint256[] memory after_, Result[] memory results)
    {
        before_ = snapshot(balances);
        results = execute(calls);
        after_ = snapshot(balances);
    }

    function execute(Call[] calldata calls) public payable returns (Result[] memory results) {
        results = new Result[](calls.length);
        uint256 value;
        for (uint256 i; i < calls.length; ++i) {
            Call calldata c = calls[i];
            value += c.value;
            uint256 gasBefore = gasleft();
            (bool ok, bytes memory data) = c.target.call{value: c.value}(c.data);
            uint256 gasUsed = gasBefore - gasleft();
            if (ok && c.checkReturn) ok = validReturn(data);
            if (!ok && !c.allowFailure) revert CallFailed(i, data);
            results[i] = Result(ok, data, gasUsed);
        }
        if (msg.value != value) revert ValueMismatch();
    }

    function transferAll(address token, address recipient) external {
        transfer(token, recipient, balance(token, address(this)));
    }

    /// @dev Forward only output generated by this sequence, preserving old holdings.
    function executeAndTransfer(Call[] calldata calls, address token, address recipient) external payable {
        uint256 before_ = balance(token, address(this));
        execute(calls);
        transfer(token, recipient, balance(token, address(this)) - before_);
    }

    function transfer(address token, address recipient, uint256 amount) internal {
        if (token == address(0)) {
            (bool ok,) = payable(recipient).call{value: amount}("");
            if (!ok) revert TransferFailed();
        } else {
            (bool ok, bytes memory data) = token.call(abi.encodeWithSignature(
                "transfer(address,uint256)", recipient, amount));
            if (!ok || !validReturn(data)) revert TransferFailed();
        }
    }

    function snapshot(Balance[] calldata balances) internal view returns (uint256[] memory values) {
        values = new uint256[](balances.length);
        for (uint256 i; i < balances.length; ++i) {
            Balance calldata b = balances[i];
            values[i] = balance(b.token, b.account);
        }
    }

    function balance(address token, address account) internal view returns (uint256) {
        return token == address(0) ? account.balance : IERC20(token).balanceOf(account);
    }

    function validReturn(bytes memory data) internal pure returns (bool) {
        if (data.length == 0) return true;
        if (data.length != 32) return false;
        uint256 value;
        assembly { value := mload(add(data, 32)) }
        return value == 1;
    }

    receive() external payable {}
}

interface IERC20 { function balanceOf(address account) external view returns (uint256); }
